
/**
 * Author:  Tiago Teixeira
 * Created: 09/11/2020
 */

/*CRIADO PARA TENTAR SOLUCIONAR O PROBLEMA QUE O WORKBENCH NÃO SALVA AS OPCOES DAS FK*/

USE LOCADORA;

/*CRIANDO FOREGIN KEY TABELA ENDERECOS*/

ALTER TABLE LOCADORA.ENDERECOS 

ADD CONSTRAINT FK_END_CLI
  FOREIGN KEY (id_cliente)
  REFERENCES LOCADORA.CLIENTES (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_END_CID
  FOREIGN KEY (id_cidade)
  REFERENCES LOCADORA.CIDADES (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*CRIANDO FOREGIN KEY TABELA CONTRATOS*/

ALTER TABLE LOCADORA.CONTRATOS
ADD CONSTRAINT FK_CARRO_CONTRATO
  FOREIGN KEY (id_carro)
  REFERENCES LOCADORA.CARROS (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_CLIENTES_CONTRATO
  FOREIGN KEY (id_cliente)
  REFERENCES LOCADORA.CLIENTES (Id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_COLABORADOR_CONTRATO
  FOREIGN KEY (id_colaborador)
  REFERENCES LOCADORA.COLABORADORES (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*CRIANDO FOREGIN KEY TABELA CLIENTES*/


ALTER TABLE LOCADORA.CLIENTES 
ADD CONSTRAINT FK_COLABORADOR_CLIENTE
  FOREIGN KEY (id_colaborador)
  REFERENCES LOCADORA.COLABORADORES (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*CRIANDO FOREGIN KEY TABELA COLABORADORES*/

ALTER TABLE LOCADORA.COLABORADORES 
ADD CONSTRAINT FK_CPF_CADASTRO_CPF
  FOREIGN KEY (Cpf_funCadastro)
  REFERENCES LOCADORA.COLABORADORES (Cpf)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*CRIANDO FOREGIN KEY TABELA CARROS*/

ALTER TABLE LOCADORA.CARROS
ADD CONSTRAINT FK_CARROS_COLABORADORES
  FOREIGN KEY (id_colaborador)
  REFERENCES LOCADORA.COLABORADORES (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

